name-template: 'Version $RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
version-template: '$MAJOR.$MINOR.$PATCH'
category-template: '### $TITLE'

version-resolver:
  major:
    labels:
      - breaking
  minor:
    labels:
      - enhancement
      - feature
  patch:
    labels:
      - bug
      - fix
      - bugfix
      - regression
      - chore
      - cleanup
      - dependencies
      - ci
      - build
      - documentation
  default: patch

categories:
  - title: 'Breaking changes'
    labels:
      - breaking
  - title: 'Features and improvements'
    labels:
      - enhancement
      - feature
  - title: 'Bug fixes'
    labels:
      - bug
      - fix
      - bugfix
      - regression
  - title: 'Maintenance'
    labels:
      - chore
      - cleanup
      - dependencies
      - ci
      - build
  - title: 'Documentation'
    labels:
      - documentation

exclude-labels:
  - no-changelog
  - skip-changelog
  - invalid

autolabeler:
  - label: ci
    files:
      - '.github/workflows/*'
  - label: documentation
    files:
      - '*.md'
  - label: bug
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: enhancement
    branch:
      - '/feature\/.+/'
      - '/enhancement\/.+/'
      - '/improve\/.+/'
    title:
      - '/^(add|implement|introduce|enhance|improve)\b/i'

template: |-
  ## What's New

  $CHANGES
