---
name: "OppaiDex"
guid: "fda53ad2-6d13-42e4-a501-a6d4514e74fc"
version: "1.0.0.0"
targetAbi: "10.11.0.0"
framework: "net8.0"
overview: "OppaiDex - definitly not a pron plugin for Jellyfin"
category: "Metadata"
owner: "Nana-kaka"
artifacts:
- "Jellyfin.Plugin.OppaiDex.dll"
changelog: >
  changelog
