name: '📝 Update Release Draft'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-label:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Apply release drafter labels
        uses: release-drafter/release-drafter/autolabeler@c2e2804cc59f45f57076a99af580d0fedb697927 # v7.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Create or update release draft
        uses: release-drafter/release-drafter@c2e2804cc59f45f57076a99af580d0fedb697927 # v7.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
